server :
   port : 8080
spring :
   application :
      name : cricket
   jackson :
      serialization:
         INDENT_OUTPUT : true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka