server.port : 8081
spring.application.name : alert
eurek.client.serviceUrl.defaultZone: http://localhost:8761/eureka
      
feign.hystrix.enabled : true
      
cricket.service.name : cricket 
      
logging.level.com.hemant.notification.feignclient.CricketFeignClient : DEBUG