server:
   port : 8081
spring:
   application:
      name : notification

eureka:
   client:
   serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
hystrix:
   command:
      default:
         circuitBreaker:
            requestVolumeThreshold : 10
            sleepWindowInMilliseconds : 10000
            errorThresholdPercentage : 50
            
logging:
   level:
      root : NONE
      com:
         netflix:
            hystrix : TRACE 
   pattern:
      console: "%d{HH:mm:ss} %-5level %logger{10} - %msg%n"   
      
            
